name: Debricked staging vulnerable functionality and scan

on: [push, pull_request]

jobs:
  debricked:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '11'
    - run: mvn -B package dependency:copy-dependencies -DoutputDirectory=dependencies -DskipTests
    - uses: debricked/vulnerable-functionality/java@v0.1.1-test
      with:
        path-to-compiled-files: 'target/classes'
        path-to-library-files: 'dependencies'
    - uses: debricked/actions/scan@v1
      env:
        DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
        UPLOAD_ALL_FILES: "true"
