name: Debricked vulnerable functionality and scan

on: [push, pull_request]

jobs:
  debricked:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: pwd
    - run: find . -name .debricked-call-graph
    - run: find . -name pom.xml
    - uses: debricked/vulnerable-functionality/java/maven@v0.8
    - run: pwd
    - run: find . -name .debricked-call-graph
    - run: find . -name pom.xml
    - uses: debricked/actions/scan@v1
    - run: pwd
    - run: find . -name .debricked-call-graph
    - run: find . -name pom.xml
      env:
        DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
        UPLOAD_ALL_FILES: "true"
