name: Debricked staging vulnerable functionality and scan

on: [push, pull_request]

jobs:
  debricked:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: pwd
    - run: find . -name .debricked-call-graph
    - run: find . -name pom.xml
    - uses: debricked/vulnerable-functionality/java/maven@master
    - run: pwd
    - run: find . -name .debricked-call-graph
    - run: find . -name pom.xml
    - uses: debricked/actions/scan@v1
      env:
        DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_STAGING_TOKEN }}
        UPLOAD_ALL_FILES: "true"
        DEBRICKED_API_URI: ${{ secrets.DEBRICKED_STAGING_URI }}
