name: Debricked staging vulnerable functionality and scan

on: [push, pull_request]

jobs:
  debricked:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: debricked/vulnerable-functionality/java/maven@v0.1.0-test
    - uses: debricked/actions/scan@v1
      env:
        DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_STAGING_TOKEN }}
        UPLOAD_ALL_FILES: "true"
        DEBRICKED_API_URI: ${{ secrets.DEBRICKED_STAGING_URI }}
